# version: "3.8"
# services:
#   sesac-codingon:
#     volumes: 
#       - /app/node_modules
#       - ./:/app/
#     build: 
#       context: .
#     ports:
#       - "8000:8000"
#   node:
#     image: "node:16"
#     working_dir: /usr/src/app
#     volumes:
#       - ./:/usr/src/app
#     ports:
#       - "8001:8000"
#     command: bash -c "npm install && node index"

version: "3.8"
services:
  react:
    volumes: 
      - /app/node_modules
      - ./react-docker:/app/
    build: 
      context: ./react-docker
    ports:
      - "3000:3000"
  node:
    volumes: 
      - /app/node_modules
      - ./compose:/app/
    build: 
      context: ./compose
    ports:
      - "8000:8000"